[workspace]
members = [
    "crates/*"
]

[workspace.package]
version = "0.0.1-alpha.1"
authors = ["Benedikt Schwab"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tum-gis/ecitygml-converter"

[workspace.dependencies]
egml = { version = "0.0.1-alpha", registry = "custom"  }
ecitygml = { version = "0.0.1-alpha", registry = "custom"  }
egraphics = { version = "0.0.1-alpha", registry = "custom" }
erosbag = { version = "0.0.1-alpha", registry = "custom" }

clap = "4.0.22"
serde = "1.0"
quick-xml = "0.26.0"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
itertools = "0.10.2"
nalgebra = "0.31.1"
parry3d-f64 = "0.11.1"
meshopt = "0.1.9"
gltf = "1.0.0"
gltf-json = "1.0.0"
chrono = "0.4.22"
